# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'finalAssessment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finalAssessment
	pod ‘Firebase/Core’	
	pod 'Firebase/Database' 
	pod 'Firebase/Auth'     
	pod 'Firebase/Storage' 
    pod ’SwiftyJSON’, ‘3.0.0’
   	pod ‘Alamofire’, ‘~> 4.0’
    pod 'JTAppleCalendar', '~> 6.0'

end
